#!/usr/bin/env python3

import skygen

lib = libgen.StdLib(libname='sky130_ht_sc_tt05')

lib.add_cell(
    cellname = 'mux2i_2',
    widthblocks = 11,
    columns = 11,
    spacepre = 'aaaaaaaacdt',
    spacepost = 'aaaaaaaaaaa',
    diffbridges = 'hhhhh hhhh',
    polyhclasses1 = 'pmmpmpmmpm',
    polyhclasses2 = 'mmjmjmmjmj',
    polybridges = 'xxvxvhxvxv',
    licon1vclasses = ('b    f', 'a    g', ' a  e ', 'aa   g', 'b    f', 'a    g', 'a    g', ' a g  ', 'a    g', ' a  g ', 'a    g'),
    licon1hclasses = ('m    m', 'm    m', ' m  m ', 'mm   m', 'm    m', 'm    m', 'm    m', ' m m  ', 'm    m', ' m  m ', 'm    m'),
    licon1orient = ('v    v', 'v    h', ' v  h ', 'vv   h', 'v    v', 'v    v', 'h    h', ' h h  ', 'h    h', ' h  h ', 'h    h'),
    polylicon1vclasses = 'c  c ccc c ',
    polylicon1hclasses = 'p  p pgc j ',
    polylicon1orient = 'v  h hhh v ',
    li1vclasses1 = ('beeeef', 'adde g', ' aeee ', 'aaceeg', 'bcceef', 'ac eeg', 'ac eeg', 'aa egg', 'aa  gg', 'aaddgg', 'aeeedg'),
    li1vclasses2 = ('beeeef', 'adde g', ' ceee ', 'aaeeeg', 'bcceef', 'ac eeg', 'ac egg', 'ac ggg', 'ad  gg', 'aaddgg', 'aeeedg'),
    li1hclasses1 = ('iiiiii', 'mmmm m', ' mmmm ', 'mmmmmm', 'mmammm', 'mm mmm', 'mm mmm', 'mm mmm', 'mu  mm', 'mmvvmm', 'mqqqnm'),
    li1hclasses2 = ('miiiim', 'mnnm m', ' pmmm ', 'mmmmmm', 'mmammm', 'mm mmm', 'mm mmm', 'mm mmm', 'mv  mm', 'mmwwmm', 'mqqqqm'),
    li1bridges = (' vvvxv ', 'v v h v', '   x h ', 'vv hx v', ' vh hx ', 'v h hhv', ' hh hhh', ' h   hh', ' hh  hh', ' h v  h', ' vvvvv '),
    polyli1vclasses1 = 'c  c ccc c ',
    polyli1vclasses2 = 'c  c ddd c ',
    polyli1hclasses1 = 'p  p ogc j ',
    polyli1hclasses2 = 'p  p ogf j ',
    polyli1bridges = '     hh    ',
    mcontypes = ('      ', ' pp   ', ' m    ', '      ', '      ', '  p   ', '  p   ', '  p   ', ' m    ', '  pp  ', '    pp'),
    met1types = ('      ', '      ', ' m    ', ' m    ', ' m    ', ' m    ', ' m    ', ' m    ', ' m    ', '      ', '      '),
    met1bridges = ('      ', '      ', ' h    ', ' h    ', ' h    ', ' h    ', ' h    ', ' h    ', '      ', '      ', '      '),
    inputpins = (('A0', ((5, 3), (6, 3), (7, 3))), ('A1', ((9, 3), (9, 4))), ('S', ((1, 3),))),
    outputpins = (('Y', ((10, 5), (10, 6))),),)

lib.add_cell(
    cellname = 'maj3_2',
    widthblocks = 9,
    columns = 9,
    spacepre = 'beaaaaeqa',
    spacepost = 'aaaaaaaaa',
    diffbridges = 'hhhhhhhh',
    polyhclasses1 = 'opmpmmpm',
    polyhclasses2 = 'omjmjmmj',
    polybridges = 'vxvxvvxv',
    licon1vclasses = ('a   gg', '      ', 'a    g', '      ', 'a   gg', '      ', 'a   gg', 'aa ggg', 'aa ggg'),
    licon1hclasses = ('m   mm', '      ', 'm    m', '      ', 'm   mm', '      ', 'm   mm', 'mm mmm', 'mm mmm'),
    licon1orient = ('h   hh', '      ', 'h    h', '      ', 'h   hh', '      ', 'h   hh', 'hh hhh', 'vv vvv'),
    polylicon1vclasses = 'cc c cc  ',
    polylicon1hclasses = 'ow w mp  ',
    polylicon1orient = 'vv v vv  ',
    li1vclasses1 = ('aaddgg', ' adgg ', 'aadggg', ' adgg ', 'aadggg', ' add  ', 'aac gg', 'aadggg', 'aa ggg'),
    li1vclasses2 = ('aaddgg', ' adgg ', 'aadggg', ' adgg ', 'aadggg', ' adg  ', 'aac gg', 'aadggg', 'aa ggg'),
    li1hclasses1 = ('lhhhll', ' mkkm ', 'mmmmmm', ' momm ', 'mimmmm', ' mss  ', 'muu mm', 'mmqmmm', 'mm mmm'),
    li1hclasses2 = ('mqhhmm', ' mkkm ', 'mmmmmm', ' momm ', 'mqqmmm', ' mss  ', 'muu mm', 'mmqmmm', 'mm mmm'),
    li1bridges = (' vxvvx ', '  hvhh ', 'v hhhhv', '  h hh ', ' vh hv ', '  hv   ', 'v v  vv', ' vvvvv ', 'vv  vvv'),
    polyli1vclasses1 = 'cc c cc  ',
    polyli1vclasses2 = 'cc c cc  ',
    polyli1hclasses1 = 'ow w mp  ',
    polyli1hclasses2 = 'vw w mp  ',
    polyli1bridges = '         ',
    mcontypes = ('      ', '  p   ', '  p   ', '  p   ', '  p   ', '  pp  ', '      ', 'p     ', '      '),
    met1types = ('      ', '      ', '      ', '      ', '      ', '      ', '      ', '      ', '      '),
    met1bridges = ('      ', '      ', '      ', '      ', '      ', '      ', '      ', '      ', '      '),
    inputpins = (('A', ((2, 3), (3, 3))), ('B', ((4, 3),)), ('C', ((1, 3), (5, 3), (5, 4)))),
    outputpins = (('X', ((7, 1),)),),)

lib.add_cell(
    cellname = 'dlrtp_1',
    widthblocks = 15,
    columns = 14,
    spacepre = 'aaaagmmmgaagga',
    spacepost = 'aaaaaaaaaaaaaa',
    diffbridges = 'hh hhhhhh hhh',
    polyhclasses1 = 'ammemmmmpmjmp',
    polyhclasses2 = 'jmmjmmmm\x7dmjmp',
    polybridges = 'vv vvvvvv vvv',
    licon1vclasses = (' a  ff', 'a    g', 'b   ff', 'b   ff', 'a   gg', '     g', ' a   g', 'a    g', 'a     ', 'a    g', 'a    g', '    dg', 'a    g', 'a   gg'),
    licon1hclasses = (' m  mm', 'm    m', 'm   mm', 'm   mm', 'm   mm', '     m', ' m   m', 'm    m', 'm     ', 'm    m', 'm    m', '    mm', 'm    m', 'm   mm'),
    licon1orient = (' h  hv', 'h    h', 'v   vv', 'v   vv', 'h   vv', '     h', ' h   h', 'h    h', 'h     ', 'v    v', 'h    v', '    hh', 'v    v', 'h   hh'),
    polylicon1vclasses = 'cc cccccc ccc ',
    polylicon1hclasses = 'am emmmm\x7d jmp ',
    polylicon1orient = 'vv hvhhhv hhv ',
    li1vclasses1 = (' addff', 'aacdfg', 'b   ef', 'bc dff', 'acddgg', 'dddddg', ' acddg', 'acdddg', 'accddg', 'accddg', 'accddg', 'dddddg', 'a cd g', 'abdddg'),
    li1vclasses2 = (' addff', 'aacdfg', 'c   ef', 'bc dff', 'acddgg', 'dddddg', ' cdddg', 'acdddg', 'adcddg', 'accddg', 'accddg', 'dddddg', 'a cd g', 'ddddgg'),
    li1hclasses1 = (' mkkmm', 'mmmmmm', 'm   mm', 'mm mmm', 'mmmmmm', 'gnnngm', ' mzzmm', 'mmxxxm', 'muuuqq', 'mssssm', 'hdttdm', 'ssssmm', 'm zz m', 'mwwwmm'),
    li1hclasses2 = (' mllmm', 'mmnnmm', 'p   pp', 'mm mmm', 'mmmmmm', 'nnnnnm', ' m{{mm', 'mmxxxm', 'muuvuq', 'mssssm', 'mdtudm', 'tttsom', 'm zz m', 'swwwss'),
    li1bridges = ('  hv x ', 'v vvv v', '     v ', ' vh xv ', 'v vv vv', ' vvvvhh', '  hv h ', ' hhvv h', '  vvvv ', 'v xvvhx', ' v v hv', ' vv x  ', 'v  v  v', ' vvvvv '),
    polyli1vclasses1 = 'cc cccccc ccc ',
    polyli1vclasses2 = 'cc dccdcc ccc ',
    polyli1hclasses1 = 'ai ekmmm\x7d jmp ',
    polyli1hclasses2 = 'am emmmm\x7d jmp ',
    polyli1bridges = '              ',
    mcontypes = ('  pp  ', '   m  ', 'm   m ', '  p   ', '      ', 'm   m ', '      ', '   m  ', '      ', '   m  ', '      ', '   m  ', 'ppp   ', '      ', 'p   pp'),
    met1types = ('      ', '   m  ', 'm  mm ', 'm  mm ', 'm  mm ', 'm  mm ', '   m  ', '   m  ', '      ', '   m  ', '   m  ', '   m  ', '      ', '      ', '      '),
    met1bridges = ('      ', '   h  ', 'h  hh ', 'h  hh ', 'h  hh ', '   h  ', '   h  ', '      ', '      ', '   h  ', '   h  ', '      ', '      ', '      ', '      '),
    inputpins = (('GATE', ((0, 3), (0, 4))), ('D', ((3, 3),)), ('RESET_B', ((12, 1), (12, 2), (12, 3)))),
    outputpins = (('Q', ((14, 1), (14, 5), (14, 6))),),)

lib.add_cell(
    cellname = 'dfrtp_1',
    widthblocks = 23,
    columns = 23,
    spacepre = 'ccccccccccccccccccccccc',
    spacepost = 'ccccccccccccccccccccccc',
    diffbridges = 'hhhhhhhhhhhhhhhhhhhhhhh',
    polyhclasses1 = 'mmmmmmmmmmmmmmmmmmmmmmm',
    polyhclasses2 = 'mmmmmmmmmmmmmmmmmmmmmmm',
    polybridges = 'xxxxxxxxxxxxxxxxxxxxxv',
    licon1vclasses = ('      ', '     g', '     g', 'aacggg', '     g', '     g', ' acgg ', 'aa  gg', 'aa  gg', ' acgg ', '      ', 'aacggg', 'a    g', 'aa  gg', ' acgg ', '      ', ' acgg ', 'aa  gg', 'aa  gg', ' acgg ', '      ', '      ', '      '),
    licon1hclasses = ('      ', '     m', '     m', 'mmmmmm', '     m', '     m', ' mmmm ', 'mm  mm', 'mm  mm', ' mmmm ', '      ', 'mmmmmm', 'm    m', 'mm  mm', ' mmmm ', '      ', ' mmmm ', 'mm  mm', 'mm  mm', ' mmmm ', '      ', '      ', '      '),
    licon1orient = ('      ', '     h', '     h', 'hhhhhh', '     h', '     h', ' hhhh ', 'hh  hh', 'hh  hh', ' hhhh ', '      ', 'hhhhhh', 'h    h', 'hh  hh', ' hhhh ', '      ', ' hhhh ', 'hh  hh', 'hh  hh', ' hhhh ', '      ', '      ', '      '),
    polylicon1vclasses = '                       ',
    polylicon1hclasses = '                       ',
    polylicon1orient = '                       ',
    li1vclasses1 = ('      ', '     g', '     g', 'aacggg', 'd    g', '     g', ' acgg ', 'aa  gg', 'aa  gg', 'dacgg ', '      ', 'aacggg', 'a    g', 'aa  gg', 'dacgg ', '      ', ' acgg ', 'aa  gg', 'aa  gg', 'dacgg ', '      ', '      ', '      '),
    li1vclasses2 = ('      ', '     g', '     g', 'aacggg', 'e    g', '     g', ' acgg ', 'aa  gg', 'aa  gg', 'eacgg ', '      ', 'aacggg', 'a    g', 'aa  gg', 'eacgg ', '      ', ' acgg ', 'aa  gg', 'aa  gg', 'eacgg ', '      ', '      ', '      '),
    li1hclasses1 = ('      ', '     m', '     m', 'mmmmmm', 'b    m', '     m', ' mmmm ', 'mm  mm', 'mm  mm', 'bmmmm ', '      ', 'mmmmmm', 'm    m', 'mm  mm', 'bmmmm ', '      ', ' mmmm ', 'mm  mm', 'mm  mm', 'bmmmm ', '      ', '      ', '      '),
    li1hclasses2 = ('      ', '     m', '     m', 'mmmmmm', 'k    m', '     m', ' mmmm ', 'mm  mm', 'mm  mm', 'kmmmm ', '      ', 'mmmmmm', 'm    m', 'mm  mm', 'kmmmm ', '      ', ' mmmm ', 'mm  mm', 'mm  mm', 'kmmmm ', '      ', '      ', '      '),
    li1bridges = ('       ', '      h', '      h', ' vvvvvh', '      h', '       ', '  xvvh ', ' xh  xh', ' vh  x ', '  vvv  ', '       ', ' xvvvvh', ' h    h', ' vh  x ', '  vvv  ', '       ', '  xvvh ', ' xh  xh', ' vh  x ', '  vvv  ', '       ', '       ', '       '),
    polyli1vclasses1 = '                       ',
    polyli1vclasses2 = '                       ',
    polyli1hclasses1 = '                       ',
    polyli1hclasses2 = '                       ',
    polyli1bridges = '                       ',
    mcontypes = ('      ', '      ', '      ', '      ', 'p     ', '      ', '      ', '      ', '      ', 'p     ', '      ', '      ', '      ', '      ', 'p     ', '      ', '      ', '      ', '      ', 'p     ', '      ', '      ', '      '),
    met1types = ('      ', '     m', '     m', 'mmmmmm', '     m', '     m', ' mmmm ', 'mm  mm', 'mm  mm', ' mmmm ', '      ', 'mmmmmm', 'm    m', 'mm  mm', ' mmmm ', '      ', ' mmmm ', 'mm  mm', 'mm  mm', ' mmmm ', '      ', '      ', '      '),
    met1bridges = ('      ', '     h', '     h', 'vvvvvh', '     h', '      ', ' xvvh ', 'x   vh', 'vh  x ', ' vvv  ', '      ', 'xvvvvh', 'h    h', 'vh  x ', ' vvv  ', '      ', ' xvvh ', 'x   vh', 'vh  x ', ' vvv  ', '      ', '      ', '      '),
    inputpins = (('CLK', ((4, 1),)), ('D', ((9, 1),)), ('RESET_B', ((14, 1),))),
    outputpins = (('Q', ((19, 1),)),),)

lib.write_outputs()

