#!/usr/bin/env python3

import skygen

lib = skygen.StdLib(libname='sky130_ht_sc_tt05')

lib.add_cell(
    cellname = 'mux2i_2',
    widthblocks = 11,
    columns = 11,
    spacepre = 'aaaaaaaacdt',
    spacepost = 'aaaaaaaaaaa',
    diffbridges = 'hhhhh hhhh',
    polyhclasses1 = 'pmmpmpmmpm',
    polyhclasses2 = 'mmjmjmmjmj',
    polybridges = 'xxvxvhxvxv',
    licon1vclasses = ('b    f', 'a    g', ' a  e ', 'aa   g', 'b    f', 'a    g', 'a    g', ' a g  ', 'a    g', ' a  g ', 'a    g'),
    licon1hclasses = ('m    m', 'm    m', ' m  m ', 'mm   m', 'm    m', 'm    m', 'm    m', ' m m  ', 'm    m', ' m  m ', 'm    m'),
    licon1orient = ('v    v', 'v    h', ' v  h ', 'vv   h', 'v    v', 'v    v', 'h    h', ' h h  ', 'h    h', ' h  h ', 'h    h'),
    polylicon1vclasses = 'c  c ccc c ',
    polylicon1hclasses = 'p  p pgc j ',
    polylicon1orient = 'v  h hhh v ',
    li1vclasses1 = ('beeeef', 'adde g', ' aeee ', 'aaceeg', 'bcceef', 'ac eeg', 'ac eeg', 'aa egg', 'aa  gg', 'aaddgg', 'aeeedg'),
    li1vclasses2 = ('beeeef', 'adde g', ' ceee ', 'aaeeeg', 'bcceef', 'ac eeg', 'ac egg', 'ac ggg', 'ad  gg', 'aaddgg', 'aeeedg'),
    li1hclasses1 = ('iiiiii', 'mmmm m', ' mmmm ', 'mmmmmm', 'mmammm', 'mm mmm', 'mm mmm', 'mm mmm', 'mu  mm', 'mmvvmm', 'mqqqnm'),
    li1hclasses2 = ('miiiim', 'mnnm m', ' pmmm ', 'mmmmmm', 'mmammm', 'mm mmm', 'mm mmm', 'mm mmm', 'mv  mm', 'mmwwmm', 'mqqqqm'),
    li1bridges = (' vvvxv ', 'v v h v', '   x h ', 'vv hx v', ' vh hx ', 'v h hhv', ' hh hhh', ' h   hh', ' hh  hh', ' h v  h', ' vvvvv '),
    polyli1vclasses1 = 'c  c ccc c ',
    polyli1vclasses2 = 'c  c ddd c ',
    polyli1hclasses1 = 'p  p ogc j ',
    polyli1hclasses2 = 'p  p ogf j ',
    polyli1bridges = '     hh    ',
    mcontypes = ('      ', ' pp   ', ' m    ', '      ', '      ', '  p   ', '  p   ', '  p   ', ' m    ', '  pp  ', '    pp'),
    met1types = ('      ', '      ', ' m    ', ' m    ', ' m    ', ' m    ', ' m    ', ' m    ', ' m    ', '      ', '      '),
    met1bridges = ('      ', '      ', ' h    ', ' h    ', ' h    ', ' h    ', ' h    ', ' h    ', '      ', '      ', '      '),
    inputpins = (('A0', ((5, 3), (6, 3), (7, 3))), ('A1', ((9, 3), (9, 4))), ('S', ((1, 3),))),
    outputpins = (('Y', ((10, 5), (10, 6))),),)

lib.add_cell(
    cellname = 'maj3_2',
    widthblocks = 9,
    columns = 9,
    spacepre = 'beaaaaeqa',
    spacepost = 'aaaaaaaaa',
    diffbridges = 'hhhhhhhh',
    polyhclasses1 = 'opmpmmpm',
    polyhclasses2 = 'omjmjmmj',
    polybridges = 'vxvxvvxv',
    licon1vclasses = ('a   gg', '      ', 'a    g', '      ', 'a   gg', '      ', 'a   gg', 'aa ggg', 'aa ggg'),
    licon1hclasses = ('m   mm', '      ', 'm    m', '      ', 'm   mm', '      ', 'm   mm', 'mm mmm', 'mm mmm'),
    licon1orient = ('h   hh', '      ', 'h    h', '      ', 'h   hh', '      ', 'h   hh', 'hh hhh', 'vv vvv'),
    polylicon1vclasses = 'cc c cc  ',
    polylicon1hclasses = 'ow w mp  ',
    polylicon1orient = 'vv v vv  ',
    li1vclasses1 = ('aaddgg', ' adgg ', 'aadggg', ' adgg ', 'aadggg', ' add  ', 'aac gg', 'aadggg', 'aa ggg'),
    li1vclasses2 = ('aaddgg', ' adgg ', 'aadggg', ' adgg ', 'aadggg', ' adg  ', 'aac gg', 'aadggg', 'aa ggg'),
    li1hclasses1 = ('lhhhll', ' mkkm ', 'mmmmmm', ' momm ', 'mimmmm', ' mss  ', 'muu mm', 'mmqmmm', 'mm mmm'),
    li1hclasses2 = ('mqhhmm', ' mkkm ', 'mmmmmm', ' momm ', 'mqqmmm', ' mss  ', 'muu mm', 'mmqmmm', 'mm mmm'),
    li1bridges = (' vxvvx ', '  hvhh ', 'v hhhhv', '  h hh ', ' vh hv ', '  hv   ', 'v v  vv', ' vvvvv ', 'vv  vvv'),
    polyli1vclasses1 = 'cc c cc  ',
    polyli1vclasses2 = 'cc c cc  ',
    polyli1hclasses1 = 'ow w mp  ',
    polyli1hclasses2 = 'vw w mp  ',
    polyli1bridges = '         ',
    mcontypes = ('      ', '  p   ', '  p   ', '  p   ', '  p   ', '  pp  ', '      ', 'p     ', '      '),
    met1types = ('      ', '      ', '      ', '      ', '      ', '      ', '      ', '      ', '      '),
    met1bridges = ('      ', '      ', '      ', '      ', '      ', '      ', '      ', '      ', '      '),
    inputpins = (('A', ((2, 3), (3, 3))), ('B', ((4, 3),)), ('C', ((1, 3), (5, 3), (5, 4)))),
    outputpins = (('X', ((7, 1),)),),)

lib.add_cell(
    cellname = 'dlrtp_1',
    widthblocks = 15,
    columns = 14,
    spacepre = 'baaagmmmgaagga',
    spacepost = 'aaaaaaaaaaaaaa',
    diffbridges = 'hh hhhhhh hhh',
    polyhclasses1 = 'ammemmmmpjjmp',
    polyhclasses2 = 'jmmjmmmmpjjmp',
    polybridges = 'vv vvvvvx vvv',
    licon1vclasses = (' a  ff', 'a    g', 'b   ff', 'b   ff', 'a   gg', '     g', ' a   g', 'a    g', 'a     ', 'a    g', 'a    g', '    dg', 'a    g', 'a   gg'),
    licon1hclasses = (' m  mm', 'm    m', 'm   mm', 'm   mm', 'm   mm', '     m', ' m   m', 'm    m', 'm     ', 'm    m', 'm    m', '    mm', 'm    m', 'm   mm'),
    licon1orient = (' h  hv', 'h    h', 'v   vv', 'v   vv', 'h   vv', '     h', ' h   h', 'h    h', 'h     ', 'v    v', 'h    v', '    hh', 'v    v', 'h   hh'),
    polylicon1vclasses = 'cc ccccc cccc ',
    polylicon1hclasses = 'am emmmm jjmp ',
    polylicon1orient = 'vv hvhhh vhhv ',
    li1vclasses1 = (' addff', 'aacdfg', 'b   ef', 'bc dff', 'acddgg', 'dddddg', ' acddg', 'acdddg', 'accddg', 'accddg', 'accddg', 'dddddg', 'a cd g', 'abdddg'),
    li1vclasses2 = (' addff', 'aacdfg', 'c   ef', 'bc dff', 'acddgg', 'dddddg', ' cdddg', 'acdddg', 'adcddg', 'accddg', 'accddg', 'dddddg', 'a cd g', 'ddddgg'),
    li1hclasses1 = (' mkkmm', 'mmmmmm', 'm   mm', 'mm mmm', 'mmmmmm', 'gnnngm', ' mzzmm', 'mmxxxm', 'muuuqq', 'muuuum', 'hdttdm', 'ssssmm', 'm zz m', 'mwwwmm'),
    li1hclasses2 = (' mkkmm', 'mmnnmm', 'p   pp', 'mm mmm', 'mmmmmm', 'nnnnnm', ' m{{mm', 'mmxxxm', 'muuvuq', 'muuuum', 'mdtudm', 'ssssom', 'm zz m', 'swwwss'),
    li1bridges = ('  hv x ', 'v vvv v', '     v ', ' vh xv ', 'v vv vv', ' vvvvhh', '  hv h ', ' hhvv h', '  vvvv ', 'v xvvhx', ' v v hv', ' vv x  ', 'v  v  v', ' vvvvv '),
    polyli1vclasses1 = 'cc ccccc cccc ',
    polyli1vclasses2 = 'cc dccdc cccc ',
    polyli1hclasses1 = 'ai ekmmm jjmp ',
    polyli1hclasses2 = 'am emmmm jjmp ',
    polyli1bridges = '              ',
    mcontypes = ('  pp  ', '   m  ', 'm   m ', '  p   ', '      ', 'm   m ', '      ', '   m  ', '      ', '   m  ', '      ', '   m  ', 'ppp   ', '      ', 'p   pp'),
    met1types = ('      ', '   m  ', 'm  mm ', 'm  mm ', 'm  mm ', 'm  mm ', '   m  ', '   m  ', '      ', '   m  ', '   m  ', '   m  ', '      ', '      ', '      '),
    met1bridges = ('      ', '   h  ', 'h  hh ', 'h  hh ', 'h  hh ', '   h  ', '   h  ', '      ', '      ', '   h  ', '   h  ', '      ', '      ', '      ', '      '),
    inputpins = (('GATE', ((0, 3), (0, 4))), ('D', ((3, 3),)), ('RESET_B', ((12, 1), (12, 2), (12, 3)))),
    outputpins = (('Q', ((14, 1), (14, 5), (14, 6))),),)

lib.add_cell(
    cellname = 'dfrtp_1',
    widthblocks = 21,
    columns = 22,
    spacepre = 'baaaagaagaaaaEagaiaaaa',
    spacepost = 'aaaaaaaaaaaaaaaaaaaaaa',
    diffbridges = 'hh hhhhhhh hhhhhh hhh',
    polyhclasses1 = 'jm fmmp jmpj jmmpojmp',
    polyhclasses2 = 'jm fmmp jmpj jmmpojmp',
    polybridges = 'vv vvvv vvhv vvvvhvvv',
    licon1vclasses = ('b   ff', 'a    g', 'b    f', 'aa  gg', '     f', ' a   f', 'a    g', 'a     ', '     f', '     g', 'a    f', 'a    f', 'b     ', '     f', ' a   f', 'a    g', 'a     ', 'a    g', 'a   gg', '     f', 'a    g', 'a    g'),
    licon1hclasses = ('m   mm', 'm    m', 'm    m', 'mm  mm', '     m', ' m   m', 'm    m', 'm     ', '     m', '     m', 'm    m', 'm    m', 'm     ', '     m', ' m   m', 'm    m', 'm     ', 'm    m', 'm   mm', '     m', 'm    m', 'm    m'),
    licon1orient = ('v   vv', 'v    v', 'h    h', 'vv  vv', '     v', ' h   v', 'h    h', 'h     ', '     v', '     h', 'h    v', 'h    v', 'v     ', '     v', ' h   v', 'h    h', 'h     ', 'h    v', 'h   vv', '     v', 'v    v', 'h    h'),
    polylicon1vclasses = 'cc cccc ccc  ccccc cc ',
    polylicon1hclasses = 'jm fmmp jmp  jmmpo mp ',
    polylicon1orient = 'hv hhvv vvv  vvvvv hv ',
    li1vclasses1 = ('bccdff', 'accdeg', 'bacegf', 'aacegg', '  cedf', ' acddf', 'aacddg', 'aacegg', ' aceff', ' adefg', 'aaceff', 'aaeedf', 'ba  df', '  cddf', ' acddf', 'aacddg', 'aacddg', 'aacddg', 'adc gg', 'acc df', 'accddg', 'aacggg'),
    li1vclasses2 = ('bccdff', 'accdeg', 'bacegf', 'aadegg', '  cedf', ' acddf', 'aacddg', 'aacegg', ' aceff', ' adefg', 'aaceff', 'aaeedf', 'ba  df', '  cddf', ' acddf', 'aacddg', 'aacddg', 'aacddg', 'adc gg', 'acd df', 'accddg', 'aacggg'),
    li1hclasses1 = ('mmkkmm', 'mwwmwm', 'mttttm', 'mmlmmm', '  tttm', ' mwmwm', 'mmttrm', 'mwwppp', ' muumm', ' mvmmm', 'mzzmmm', 'mrrrrm', 'mm  ii', '  wwwm', ' mvvvm', 'mmuuum', 'mmwwss', 'muuuum', 'mrr mm', 'qqt mm', 'mxxvxm', 'mxxxxm'),
    li1hclasses2 = ('mmkkmm', 'mwwwwm', 'pttttp', 'mmlmmm', '  tttm', ' mwwwm', 'mmtttm', 'mwwwpp', ' muumm', ' mvmmm', 'mzzmmm', 'mrrrrm', 'mm  ii', '  wwwm', ' mvvvm', 'mmuuum', 'mmwwss', 'muuuum', 'mrr mm', 'qqt mm', 'mxxxxm', 'txxxxt'),
    li1bridges = (' vhv x ', 'v vvv v', ' vvvxv ', 'vv  hvv', '   vvhh', '  hv h ', ' hhvv h', '  xvvv ', '  hvhx ', '  h hhv', 'vhv hv ', 'v xvvhv', ' v   vh', '   vvhh', '  hv h ', ' hhvv h', '  hv x ', 'v vvv x', ' hvh vv', ' vh  x ', 'v vvv v', ' vvvvv '),
    polyli1vclasses1 = 'cc cccc ccc  ccccc cc ',
    polyli1vclasses2 = 'cc cccc ccc  ccccc cc ',
    polyli1hclasses1 = 'jm fmmp jmp  jmmpo mp ',
    polyli1hclasses2 = 'jm fmmp jmp  jmmpo mp ',
    polyli1bridges = '                     ',
    mcontypes = ('  pp  ', '   m  ', '      ', '  p   ', '      ', '   m  ', '    m ', '      ', '      ', '  m   ', '      ', '      ', '      ', '   m  ', '    m ', '   m  ', '      ', ' p    ', '  m   ', '   m  ', 'pppppp'),
    met1types = ('      ', '   m  ', '   m  ', '   m  ', '   m  ', '   m  ', '   mm ', '   mm ', '   mm ', '  mmm ', '  mmm ', '  mmm ', '  mmm ', '  mmm ', '  m m ', '  mm  ', '  mm  ', '  mm  ', '  mm  ', '   m  ', '      '),
    met1bridges = ('      ', '   h  ', '   h  ', '   h  ', '   h  ', '   h  ', '   hh ', '   hh ', '   hh ', '  hhh ', '  hhh ', '  hhh ', '  hhh ', '  h h ', '  h   ', '  hh  ', '  hh  ', '  hh  ', '   h  ', '      ', '      '),
    inputpins = (('CLK', ((0, 3), (0, 4))), ('D', ((3, 3),)), ('RESET_B', ((17, 2),))),
    outputpins = (('Q', ((20, 1), (20, 2), (20, 3), (20, 4), (20, 5), (20, 6))),),)

lib.write_outputs()

