name: gds

on:
  push:
  workflow_dispatch:

jobs:
  gds:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Create and publish the GDS artifact
        uses: TinyTapeout/tt-gds-action/custom_gds@tt05
        with: 
          top_module: tt_um_example
          gds_path: signoff/gds/tt_um_htfab_cell_tester.gds
          lef_path: signoff/lef/tt_um_htfab_cell_tester.lef
          verilog_path: signoff/verilog/gl/tt_um_htfab_cell_tester.v
